service: ${self:custom.defaults.service}-ddb-mealOrders
frameworkVersion: ${self:custom.defaults.version}
provider:
  name: aws
  stage: ${self:custom.defaults.stage}
  region: ${self:custom.defaults.region}
  deploymentBucket:
    name: ${self:custom.defaults.service}-${self:provider.region}-${aws:accountId}
    serverSideEncryption: AES256
custom:
  base: ${self:service}-${self:provider.stage}
  defaults: ${file(../../../defaults/cloudgto.yml):defaults}
plugins:
  - serverless-deployment-bucket
resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.base}-mealOrders
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: orderItemId
            AttributeType: S
          - AttributeName: customerId
            AttributeType: S
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
          - AttributeName: orderItemId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: customer-gsi
            KeySchema:
              - AttributeName: customerId
                KeyType: HASH
              - AttributeName: orderId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        Tags:
          - Key: description
            Value: Stores orders for the meal prep service
  Outputs:
    DynamoDBTableName:
      Description: DynamoDB Table Name
      Value: ${self:custom.base}-mealOrders
    DynamoDBTableArn:
      Description: DynamoDB Table Arn
      Value:
        Fn::GetAtt:
          - DynamoDbTable
          - Arn
