service: ${self:custom.defaults.service}-ddb-mealsMenu
frameworkVersion: ${self:custom.defaults.version}
provider:
  name: aws
  stage: ${self:custom.defaults.stage}
  region: ${self:custom.defaults.region}
  deploymentBucket:
    name: ${self:custom.defaults.service}-${self:provider.region}-${aws:accountId}
    serverSideEncryption: AES256
custom:
  base: ${self:service}-${self:provider.stage}
  defaults: ${file(../../../defaults/cloudgto.yml):defaults}
plugins:
  - serverless-deployment-bucket
resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.base}-mealsMenu
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: mealId
            AttributeType: S
          - AttributeName: seller
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: mealId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: seller-gsi
            KeySchema:
              - AttributeName: seller
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: category-gsi
            KeySchema:
              - AttributeName: category
                KeyType: HASH
              - AttributeName: seller
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        Tags:
          - Key: description
            Value: Stores menu items for meal prep service
  Outputs:
    DynamoDBTableName:
      Description: DynamoDB Table Name
      Value: ${self:custom.base}-mealsMenu
    DynamoDBTableArn:
      Description: DynamoDB Table Arn
      Value:
        Fn::GetAtt:
          - DynamoDbTable
          - Arn
